export enum ThumbnailFormats {
    /** 50x75px */
    portrait_small = 'portrait_small',
    /** 100x150px */
    portrait_medium = 'portrait_medium',
    /**	150x225px */
    portrait_xlarge = 'portrait_xlarge',
    /**	168x252px */
    portrait_fantastic = 'portrait_fantastic',
    /**	300x450px */
    portrait_uncanny = 'portrait_uncanny',
    /** 216x324px */
    portrait_incredible = 'portrait_incredible',
    /** 65x45px */
    standard_small = 'standard_small',
    /** 100x100px */
    standard_medium = 'standard_medium',
    /**	140x140px */
    standard_large = 'standard_large',
    /**	200x200px */
    standard_xlarge = 'standard_xlarge',
    /** 250x250px */
    standard_fantastic = 'standard_fantastic',
    /**	180x180px */
    standard_amazing = 'standard_amazing',
    /**	120x90px */
    landscape_small = 'landscape_small',
    /** 175x130px */
    landscape_medium = 'landscape_medium',
    /** 190x140px */
    landscape_large = 'landscape_large',
    /**	270x200px */
    landscape_xlarge = 'landscape_xlarge',
    /** 250x156px */
    landscape_amazing = 'landscape_amazing',
    /** 464x261px */
    landscape_incredible = 'landscape_incredible'
}